# Optional if waysaver-daemon.service was not enabled during installation.
exec-once = systemctl --user start waysaver-daemon.service

# Optional shortcuts. Change SUPER to your preferred modifier.
bind = SUPER, F11, exec, waysaver --activate
bind = SUPER SHIFT, F11, exec, waysaver --settings

